### ISSUE TITLE
Add interfaces to allow integration of PyFluent and PySystemCoupling

### ISSUE THREAD

**Issue by ochernuk** [ansys/pysystem-coupling#148]
### 📝 Description of the feature

The motivation is to integrate PyFluent and PySystemCoupling in such a way that PySystemCoupling can orchestrate a co-simulation involving one or more PyFluent solver instances, leveraging the existing connection between Fluent and System Coupling. In order to do that, changes are needed in both PyFluent and PySystemCoupling repositories. PySystemCoupling should be able to receive a handle to the PyFluent solver (session) object and to:

issue queries via a generic interface to get the System Coupling-specific setup information related to this participant:
Regions involved in System Coupling analysis (and their properties, such as topology, etc.)
Variables involved in System Coupling analysis (and their properties, such as tensor type, etc.)
Whether the Fluent analysis is steady or transient
invoke commands to establish connection between Fluent and System Coupling and to perform a coupled solve
Some of these commands will need to be called asynchronously (perhaps on a separate thread)
It would be preferrable to avoid introducing dependencies between PyFluent and PySystemCoupling and instead to just have PyFluent provide a generic interface ("duck-typing") to PySystemCoupling to perform the above operations.

A corresponding issue will be tracked within the PyFluent repository.

### 💡 Steps for implementing the feature

...

### 🔗 Useful links and references

Corresponding issue in the PyFluent repository: https://github.com/pyansys/pyfluent/issues/1553

**Comment by iboyd-ansys** [comment]
PySystemCoupling support for this feature release in 0.3.0.
