### ISSUE TITLE
Add "start_output" argument to the launch() command to stream the output

### ISSUE THREAD

**Issue by ochernuk** [ansys/pysystem-coupling#224]
### 📝 Description of the feature

When the user launches the System Coupling session, by default the console output is not streamed in the Python console. In order to do that, the start_output() method needs to be called and then `end_output()` method should be called to stop streaming the output. For example:

```python
syc = pysyc.launch(version = "24.1")
syc.start_output()
...
syc.end_output()
syc.exit()
```

It would be good to add an argument to the `launch()` method to start the output right away, i.e.

```python
syc = pysyc.launch(version = "24.1", start_output = True)
...
syc.exit()
```

**Comment by SeunSomefun** [comment]
Completed this issue as part of the work done in PR #314
