### ISSUE TITLE
Add ability to upload files to the container seamlessly

### ISSUE THREAD

**Issue by ochernuk** [ansys/pysystem-coupling#292]
### 📝 Description of the feature

When running on Ansys Labs and adding a participant via a file, I first need to upload the file to the container, before I use it. For this, I need to first issue a separate command. It would be good to automatically upload the file to the container, as part of the `add_participant` command. This would also make the same script work using a desktop deployment, as well as cloud deployment.

### 💡 Steps for implementing the feature

Sample code (needs to be executed on Ansys Labs):

```
import ansys.systemcoupling.core as pysyc
syc = pysyc.launch()
syc.upload_file("source.scdt")
syc.setup.add_participant(input_file = "source.scdt")
```

The `upload_file` function is required currently, otherwise `add_participant` would fail. It would be good if `add_participant` function automatically detected that the file first needs to be uploaded and perform that operation.

**Comment by SeunSomefun** [comment]
Issue closed as part of the work done on PR #314
