### ISSUE TITLE
New minor version using ansys-api-systemcoupling

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pysystem-coupling#383]
Hi @ochernuk @iboyd-ansys - would it be possible to create a new minor version of PySystem Coupling using the new ansys-api-systemcoupling release (0.2.0). Currently, PySystem Coupling is the only package preventing us from upgrading to Protobuf 4.X and 5.X (from a released versions standing point). It would be great if you could get out a new version with this change.

More reference at https://github.com/ansys/ansys-tools-protoc-helper/issues/29

**Comment by iboyd-ansys** [comment]
This has been addressed by release 0.7.0.

**Comment by RobPasMue** [comment]
Awesome, thanks @iboyd-ansys!
